name: List Secret Names

# Trigger manually from the Actions tab in GitHub
on:
  push:
    branches:
      - main

jobs:
  list_secret_names:
    name: List Available Secret Names
    runs-on: ubuntu-latest
    steps:
      - name: Get and List Secret Names
        # 1. Convert the secrets context into a JSON string
        #    and store it in an environment variable.
        env:
          # This variable will contain a JSON string like:
          # {"SECRET_ONE":"***","SECRET_TWO":"***"}
          SECRETS_JSON: ${{ toJSON(secrets) }}
        run: |
          echo "Listing available secret names:"
          echo "------------------------------"

          # 2. Check if the JSON string is empty or just '{}' (no secrets)
          if [ -z "$SECRETS_JSON" ] || [ "$SECRETS_JSON" == "{}" ]; then
            echo "No secrets found or available in this context."
          else
            # 3. Use jq to parse the JSON string and extract only the keys (secret names).
            #    - 'keys' extracts an array of the object's keys (the secret names).
            #    - '[]' iterates through the elements of that array.
            #    - '-r' outputs the raw string value without JSON quotes.
            echo "$SECRETS_JSON" | jq -r 'values[]'
          fi
          echo "------------------------------"