name: List Secret Names

# Trigger manually from the Actions tab in GitHub
on:
  push:
    branches:
      - main

jobs:
  list_secret_names:
    name: List Available Secret Names
    runs-on: ubuntu-latest
    steps:
      - name: Get and List Secret Names
        # 1. Convert the secrets context into a JSON string
        #    and store it in an environment variable.
        env:
          # This variable will contain a JSON string like:
          # {"SECRET_ONE":"***","SECRET_TWO":"***"}
          SECRETS_JSON: ${{ toJSON(secrets) }}
        run: |
          echo "Listing available secret names:"
          echo "------------------------------"

          if [ -z "$SECRETS_JSON" ] || [ "$SECRETS_JSON" == "{}" ]; then
            echo "No secrets found or available in this context."
          else
            echo "$SECRETS_JSON" | jq -r 'keys[]'
          fi
          echo "------------------------------"