name: Minimal Sync GH Secrets to AWS SM (IAM User)

on:
  push:
    branches:
      - main

jobs:
  sync_secrets_minimal:
    name: Minimal Sync Secrets to AWS SM (IAM User)
    runs-on: ubuntu-latest
    env:
      # --- TODO: Set your AWS region ---
      AWS_REGION: 'eu-central-1'

    steps:
      - name: Configure AWS Credentials (IAM User)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync All Secrets (Minimal, No Error Checks)
        env:
          GITHUB_SECRETS_JSON: ${{ toJSON(secrets) }}
        run: |
          echo "Starting minimal sync to AWS Secrets Manager..."
          echo "WARNING: Errors from AWS CLI will be ignored!"

          # Extract names using jq, loop through them using 'while read'
          echo "$GITHUB_SECRETS_JSON" | jq -r 'keys[]' | while IFS= read -r secret_name; do
            # Get value via BASH indirect expansion (relies on env: ${{ secrets }})
            secret_value="${!secret_name}"

            echo "Attempting sync for: $secret_name"

            # --- Blunt "Upsert": Try create, ignore result, then try put, ignore result ---
            # 1. Attempt to create the secret. Ignore any error (e.g., if it already exists).
            aws secretsmanager create-secret --name "$secret_name" --secret-string "$secret_value" --region "$AWS_REGION" || true

            # 2. Attempt to update the secret value. Ignore any error (e.g., if create failed for some reason).
            aws secretsmanager put-secret-value --name "$secret_name" --secret-string "$secret_value" --region "$AWS_REGION" || true
          done

          echo "Minimal sync attempt finished. Check AWS Secrets Manager manually."