name: Minimal Sync GH Secrets to AWS SM (IAM User) - FIXED

# WARNING: Triggering on push to main is potentially risky for secret sync.
# Consider changing the 'on:' block below to 'on: workflow_dispatch:' for manual control.
on:
  push:
    branches:
      - main

jobs:
  sync_secrets_minimal:
    name: Minimal Sync Secrets to AWS SM (IAM User)
    runs-on: ubuntu-latest
    env:
      # AWS Region is set
      AWS_REGION: 'eu-central-1'

    steps:
      - name: Configure AWS Credentials (IAM User)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Ensure these secrets exist in your GitHub repository/organization settings
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync All Secrets (Minimal, No Error Checks)
        # The env block needs BOTH the JSON representation AND the secrets context itself
        env:
          GITHUB_SECRETS_JSON: ${{ toJSON(secrets) }}
          # --- FIX: Added missing line below to populate env variables from secrets ---
          ${{ secrets }} # Populates env vars like $SECRET_NAME with values (undocumented behavior)
        run: |
          echo "Starting minimal sync to AWS Secrets Manager..."
          echo "WARNING: Errors from AWS CLI will be ignored!"
          echo "WARNING: Relies on undocumented GitHub Actions behavior ('env: \${{ secrets }}')."

          # Extract names using jq, loop through them using 'while read'
          echo "$GITHUB_SECRETS_JSON" | jq -r 'keys[]' | while IFS= read -r secret_name; do
            # Get value via BASH indirect expansion (relies on 'env: ${{ secrets }}' having worked)
            secret_value="${!secret_name}"

            # --- FIX: Skip secrets if their value is empty to avoid AWS validation error ---
            if [ -z "$secret_value" ]; then
              echo "Skipping sync for: $secret_name (value is empty)"
              continue # Go to the next secret name in the loop
            fi

            echo "Attempting sync for: $secret_name"

            # --- Blunt "Upsert": Try create, ignore result, then try put, ignore result ---
            # 1. Attempt to create the secret. Ignore any error (e.g., if it already exists) using '|| true'.
            aws secretsmanager create-secret --name "$secret_name" --secret-string "$secret_value" --region "$AWS_REGION" || true

            # --- FIX: Changed --name to --secret-id for put-secret-value ---
            # 2. Attempt to update the secret value using the correct parameter. Ignore any error using '|| true'.
            aws secretsmanager put-secret-value --secret-id "$secret_name" --secret-string "$secret_value" --region "$AWS_REGION" || true
          done

          echo "Minimal sync attempt finished. Check AWS Secrets Manager manually."